# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 258fe1a66ff9ec64e7d10e1cb784320440e2b711819f39923b88fbde00b156bde34f38f312f8b8ee214c7257f2d81f260702a5c49fadd1b6ab95485ee19ea090

test:
  secret_key_base: 5ea29688b9b56424b1cd90326703970728b55425d09897e465f8fa74e52ad90b246155a39b03e7af6c35c016ff7f36f0a28f7debb754b8e33da1548f0eb9be1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
